### ISSUE TITLE
Lethe list is not listing disks/partition on macOS Big Sur

### ISSUE THREAD

**Issue by shadowwalkersteam** [Kostassoid/lethe#20]
I've tried lethe list and it prints empty line on terminal. I've macOS Big Sur installed, What could be the issue? Can you please help?

**Comment by Kostassoid** [comment]
Sorry for a slow response, I'm travelling. 
I haven't tested Lethe on Big Sur yet. One very simple suggestion is to make sure you run the app with `sudo`. It still won't work with the system drives though because there's a low level protection in Mac OS from doing that. But it should work on Bootcamp partition and any external drives/USBs. Let me know if that doesn't explain the behavior you're seeing. I would also appreciate a bit more info, like HW configuration and `diskutil list` output.

**Comment by shadowwalkersteam** [comment]
I've tried with sudo and yest it worked. But without sudo it doesn't even show the external pendrives connected.

**Comment by Kostassoid** [comment]
Thank you for the feedback, I'm glad the app is working at least. The ergonomics aren't so great yet, I agree. macOS in general is stricter in terms of permissions for accessing system on a low level. And because the app isn't just listing the devices but also queries additional information, it requires elevated privileges. I'll see if I can make it clearer from the app.

**Comment by shadowwalkersteam** [comment]
@Kostassoid  on another note, When I run Lethe on Windows it lists the physical drive + physical drive partitions like /harddisk1/partition1 etc. When I execute command with Physical Hard drive ID it doesn't wipe the drive like //./PhysicalDrive1, In this case it shows access denied but when I use Physical Drive partition number as the parameter then it wipes the drive like /harddisk1/partition1 etc etc

**Comment by Kostassoid** [comment]
@shadowwalkersteam Yes, that is a known issue. On Windows, all partitions have to be locked and unmounted in order to access physical drive directly, I didn't get this behavior first time I was working on the implementation for some reason. I already have a fix for it but I need to finish with the similar changes for other platforms. Thanks for bringing this up.

**Comment by Kostassoid** [comment]
Both of the mentioned issues should be fixed now. Listing devices on Windows still requires `sudo`, but on my macOS (Catalina) it's not required.
